package Mapeos;
// Generated 30-mar-2016 22:44:24 by Hibernate Tools 4.3.1



/**
 * AlumnoTieneEscuela generated by hbm2java
 */
public class AlumnoTieneEscuela  implements java.io.Serializable {


     private int idAlumnoTe;
     private int idEscuelaTe;

    public AlumnoTieneEscuela() {
    }

    public AlumnoTieneEscuela(int idAlumnoTe, int idEscuelaTe) {
       this.idAlumnoTe = idAlumnoTe;
       this.idEscuelaTe = idEscuelaTe;
    }
   
    public int getIdAlumnoTe() {
        return this.idAlumnoTe;
    }
    
    public void setIdAlumnoTe(int idAlumnoTe) {
        this.idAlumnoTe = idAlumnoTe;
    }
    public int getIdEscuelaTe() {
        return this.idEscuelaTe;
    }
    
    public void setIdEscuelaTe(int idEscuelaTe) {
        this.idEscuelaTe = idEscuelaTe;
    }




}


